PROGS = logic-analyzer.c

# /Users/clarawang/Documents/cs140e-26win/labs/7-uart/3-sw-uart-put8/sw-uart.c


COMMON_SRC += $(CS140E_2026_PATH)/libpi/src/sw-uart.c
STAFF_OBJS += $(CS140E_2026_PATH)/libpi/staff-objs/interrupts-asm.o
STAFF_OBJS += $(CS140E_2026_PATH)/libpi/staff-objs/interrupts-vec-asm.o

# automatically run the code
RUN = 0

# if you need to override the install
BOOTLOADER = my-install

include $(CS140E_2026_PATH)/libpi/mk/Makefile.robust-v2
